default:
    image: node:20-alpine
    before_script:
        - apk add --no-cache aws-cli

stages:
  - deploy

deploy:      
  stage: deploy  
  environment: production
  script:    
    - npm install
    - npm run build
