default:
    image: node:20-alpine
    before_script:
        - apk add --no-cache aws-cli

stages:
  - deploy

deploy:
  stage: deploy
  environment: production
  script:
    - npm install
    - npm run build
    - aws s3 sync ./dist s3://portal-cdn-bco.service.zingplay.com/public/editor --delete
