version: '3'
services:
  web-os:
    image: ghcr.io/remtori/web-os:latest
    ports:
      - 35696:5696
    restart: unless-stopped
    deploy:
      mode: replicated
      replicas: 3
      endpoint_mode: vip
  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command:
      - "--interval"
      - "30"
      - "--rolling-restart"
