version: '3'
services:
  api:
    image: ghcr.io/remtori/web-os-api:latest
    env_file: .env
    port:
      - 5696:5696
    restart: unless-stopped
  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command:
      - "--interval"
      - "30"
      - "--rolling-restart"
