on:
  push:
    branches:
      - main
    paths:
      - "functions/**"

jobs:
  deploy_api:
    runs-on: ubuntu-latest
    environment: 'v2 deploy'
    permissions:
      contents: read
      packages: write
    name: deploy-server
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: https://ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: functions/
          push: true
          platforms: "linux/arm64,linux/amd64"
          tags: ghcr.io/remtori/web-os-api:latest
