on:
  push:
    branches:
      - main
    paths:
      - "functions/**"
  workflow_dispatch:

jobs:
  deploy_api:
    runs-on: ubuntu-latest
    environment: 'v2 deploy'
    permissions:
      contents: read
      packages: write
    name: deploy-server
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: https://ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name:
        uses: pnpm/action-setup@v4
        run: pnpm install && pnpm run build
        env:
          FIREBASE_PROJECT_ID: ${{ vars.FIREBASE_PROJECT_ID }}
          FIREBASE_CLIENT_EMAIL: ${{ vars.FIREBASE_CLIENT_EMAIL }}
          FIREBASE_CLIENT_API_KEY: ${{ vars.FIREBASE_CLIENT_API_KEY }}
          FIREBASE_CLIENT_MESSAGING_SENDER_ID: ${{ vars.FIREBASE_CLIENT_MESSAGING_SENDER_ID }}
          FIREBASE_CLIENT_APP_ID: ${{ vars.FIREBASE_CLIENT_APP_ID }}
          FIREBASE_CLIENT_MEASUREMENT_ID: ${{ vars.FIREBASE_CLIENT_MEASUREMENT_ID }}
      - name: Push to registry
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          platforms: "linux/arm64,linux/amd64"
          tags: ghcr.io/remtori/web-os-api:latest
