on:
  push:
    branches:
      - main

jobs:
  publish_static:
    runs-on: ubuntu-latest
    environment: 'v2 deploy'
    permissions:
      contents: read
      deployments: write
    name: deploy-static
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build
        run: npm install && npm run build:web
        env:
          FIREBASE_PROJECT_ID: ${{ vars.FIREBASE_PROJECT_ID }}
          FIREBASE_CLIENT_EMAIL: ${{ vars.FIREBASE_CLIENT_EMAIL }}
          FIREBASE_CLIENT_API_KEY: ${{ vars.FIREBASE_CLIENT_API_KEY }}
          FIREBASE_CLIENT_MESSAGING_SENDER_ID: ${{ vars.FIREBASE_CLIENT_MESSAGING_SENDER_ID }}
          FIREBASE_CLIENT_APP_ID: ${{ vars.FIREBASE_CLIENT_APP_ID }}
          FIREBASE_CLIENT_MEASUREMENT_ID: ${{ vars.FIREBASE_CLIENT_MEASUREMENT_ID }}
      - name: Publish to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: a3900b672541bad0e93684916832e4aa
          projectName: web-os
          directory: dist/
          branch: main
          wranglerVersion: '3'
  publish_server:
    runs-on: ubuntu-latest
    environment: 'v2 deploy'
    permissions:
      contents: read
      packages: write
    name: deploy-server
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: https://ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: functions/
          push: true
          tags: ghcr.io/remtori/web-os-api:latest
